# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_person_editdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='person',
            name='editdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(b'F', b'\xe7\x94\xb7'), (b'M', b'\xe5\xa5\xb3')], default=None, max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
