# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20161229_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published'), (b'w', b'Withdrawn')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
