# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 04:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='context',
            field=DjangoUeditor.models.UEditorField(default=2, verbose_name='\u7b80\u4ecb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='\u6700\u5927\u957f\u5ea6\u4e3a50', max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[(b'd', b'\xe8\x8d\x89\xe7\xa8\xbf'), (b'p', b'\xe5\xb7\xb2\xe5\x8f\x91\xe5\xb8\x83'), (b'w', b'\xe5\xbe\x85\xe5\x8f\x91\xe5\xb8\x83')], max_length=1, verbose_name='\u53d1\u5e03\u72b6\u6001'),
        ),
    ]
